from agno.agent import Agent
from agno.models.google import Gemini
from agno.tools.scrapegraph import ScrapeGraphTools
from agno.tools.file import FileTools
from agno.tools.exa import ExaTools
from agno.tools.reasoning import ReasoningTools
from docx import Document
from docx.shared import Pt
from docx.oxml.ns import qn
import re
from dotenv import load_dotenv
import os
import streamlit as st

load_dotenv()

id=os.getenv("id")
api_key=os.getenv("api_key")


Data_Scraper=Agent(
    name="EU regulation crawler agent",
    model=Gemini(id=id,api_key=api_key),
    tools=[ReasoningTools(add_instructions=True),FileTools(), ScrapeGraphTools(), ExaTools(include_domains=["eur-lex.europa.eu", "ec.europa.eu"])],
    show_tool_calls=True,
    
    description="""
    Specialized agent for crawling and extracting compliance-relevant information about European regulations affecting a specific company and industry. Focuses on trusted EU sources such as EUR-Lex and the European Commission website.
    """
    ,
    instructions="""
    You are a compliance-focused data scraping agent. Your role is to gather detailed, structured, and relevant information about a given company's regulatory environment in Europe, based on its industry. You are primarily responsible for collecting recent European regulations, directives, press releases, and legal documents that may affect the company.

    Follow these steps:

    1. Understand the target company and its industry context from the user input.

    2. Use `ExaTools` to search for recent legal documents, directives, or press releases on:
    - https://eur-lex.europa.eu/homepage.html (for legislation and directives)
    - https://ec.europa.eu/commission/presscorner/home/en (for press releases and regulatory announcements)

    3. Use `ScrapeGraphTools` to extract detailed data from any relevant pages found.

    4. Focus on identifying potential compliance areas such as:
    - Data privacy (e.g. GDPR)
    - AI regulation (e.g. EU AI Act)
    - Environmental directives
    - Industry-specific regulations

    5. If no regulations are found that specifically name the company, fall back to summarizing recent EU laws or directives that are highly likely to affect the industry. For example:
    - If no AI laws mention the company, summarize how the EU AI Act impacts the industry generally.

    6. Structure the findings into a clear and detailed Doc file using `FileTools`. The file should include:
    - A metadata section at the top with:
        - Company name
        - Industry
        - Report generation date
        - List of data sources used
    - A table of contents or logical section headers
    - Categorized summaries (e.g. AI, Sustainability, Data Privacy)
    - Direct source links to each regulation
    - Dates of publication or enforcement

    7. Save the final file with the name `compliance_{company_name}.docx` using FileTools.

    Only return verified and relevant information from the specified EU sources. Ignore speculative or opinion-based content. Prioritize factual, legal, and up-to-date documents from official EU regulatory domains.
    """
    ,
    markdown=True,
    stream=True,
    success_criteria="the agent HAS to generate the final file `compliance_{company_name}.docx` using `FileTools`"
        
)



Data_Analyzer=Agent(
    name="Data Analyzer",
    model=Gemini(id=id,api_key=api_key),
    tools=[FileTools(),],
    show_tool_calls=True,
    description="""
    Analytical agent that interprets structured compliance files generated by the EU Regulation Crawler Agent. It provides legally grounded answers based only on the content of the input file.
    """,

    instructions="""
    You are a regulatory compliance analysis agent. Your job is to read a structured compliance file `compliance_{company_name}.docx` generated by the Data_Scraper agent. This file contains summaries of EU regulations, categorized by topic and linked to their sources.

    Your goal is to answer user questions like:
    - "Is there any new EU directive affecting us as a car manufacturer?"
    - "Does the EU AI Act apply to our use of AI in predictive maintenance?"
    - "Are there any emissions-related regulations we need to follow in 2025?"

    Workflow:
    1. Load the structured Doc file `compliance_{company_name}.docx` using `FileTools`.
    2. Analyze the content by scanning all sections: AI, Privacy, Sustainability, Financial, etc.
    3. Use only the contents of the loaded file to answer the question. Do not rely on external knowledge.
    4. If the answer is found, provide:
       - A clear explanation in plain English
       - A direct quote or reference from the file
       - The name and date of the regulation (if available)
       - A link to the source (if provided)
    5. If the information is **not available**, politely respond that no relevant regulation was found **within the provided file**, and suggest re-running the Data_Scraper for an updated report.

    Answer clearly and precisely, grounded only in the contents of the given file.
    """,
    markdown=True,
    stream=True,
)

if __name__ == "__main__":

    st.title("EU Regulation Compliance Scraper & Analyzer")

    company_name = st.text_input("Enter the company name:")
    industry_name = st.text_input("Enter the industry:")

    search_button = st.button("Run Data Scraper")
    output_path = f"compliance_{company_name}.docx"

    if search_button:
        query = f"Find the most recent EU directives or regulations that apply to {company_name} in the {industry_name} sector. Structure the results in a clear compliance report and save directly as a .docx file."
        st.info("Running Data Scraper... This may take a few minutes.")

        # Exécution Data Scraper
        Data_Scraper.run(query)

        if os.path.exists(output_path):
            st.success(f"Report generated successfully: {output_path}")
            st.download_button("Download Compliance Report", output_path, file_name=f"{company_name}_compliance_report.docx")
        else:
            st.error("Something went wrong. The file was not generated.")

    analyze_button = st.button("Ask a question about the compliance report")

    if analyze_button:
        user_question = st.text_input("Enter your question:")
        if user_question:
            if not os.path.exists(output_path):
                st.warning("The compliance report does not exist. Please run the Data Scraper first.")
            else:
                # Obtenir la réponse
                response = Data_Analyzer.run(user_question)
                st.markdown("**Answer:**")
                st.write(response)

